image: atlassian/docker-release-maker:latest

pipelines:
  custom:
    create-new-releases:
      - step:
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='atlassian/confluence-server'
            - export DOCKERFILE_VERSION_ARG='CONFLUENCE_VERSION'
            - export MAC_PRODUCT_KEY='confluence'
            - export TAG_SUFFIXES='adoptopenjdk8,jdk8,ubuntu,ubuntu-18.04-adoptopenjdk8'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --create
    create-custom-release:
      - variables:
          - name: CONFLUENCE_VERSION
          - name: DOCKER_TAG
      - step:
          services:
            - docker
          script:
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - docker build -t atlassian/confluence-server:${DOCKER_TAG} --build-arg CONFLUENCE_VERSION=${CONFLUENCE_VERSION} .
            - docker push atlassian/confluence-server:${DOCKER_TAG}
  branches:
    base-6-adoptopenjdk8:
      - step:
          services:
            - docker
          script:
            - export BASE_VERSION='6'
            - export DEFAULT_RELEASE='true'
            - export DOCKER_REPO='atlassian/confluence-server'
            - export DOCKERFILE_VERSION_ARG='CONFLUENCE_VERSION'
            - export MAC_PRODUCT_KEY='confluence'
            - export TAG_SUFFIXES='adoptopenjdk8,jdk8,ubuntu,ubuntu-18.04-adoptopenjdk8'
            - echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
            - python /usr/src/app/run.py --update